language: python
python:
 - "3.5"
 - "3.6"
 - "nightly"
 - "pypy3"

install:
 - pip install .
 - pip install -r requirements.txt

script: nosetests --processes=4 --with-coverage tests

after_success:
    coveralls
