language: python
python:
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "nightly"
 - "pypy3"

install:
 - pip install .
 - pip install -r requirements.txt

script: coverage run --source miniutils -m unittest discover -s tests

after_success:
    coveralls
